### ISSUE TITLE
Microsoft VC Compiler Incompatibility

### ISSUE THREAD

**Issue by beecksche** [aimukhin/fourier#1]
Unfortunately, in Microsoft VC Compiler (2019) C99 standard is not fully implemented. I'll got a number of errors while compiling. The problem seems to be the complex number (complex.h). In MSVC only [these features](https://docs.microsoft.com/de-de/cpp/c-runtime-library/complex-math-support?view=msvc-160) are supported.

Are there any plans to support also the MSVC compiler in future releases?

**Comment by aimukhin** [comment]
Thank you for reporting the issue.

It's a pity MSVC behaves like that. About support - well, I would rather prefer for my library to adhere to standards, not to specific compilers...

In the meantime, please try to change a definition in minfft.h from
`typedef double complex minfft_cmpl;`
to
`typedef _Dcomplex minfft_cmpl;`
and see if it helps.

**Comment by aimukhin** [comment]
@beecksche did this solve the issue?

**Comment by beecksche** [comment]
I've started to implement it, but hadn't time to test it yet.

Unfortunately it's not done with only replace `typedef double complex minfft_cmpl` with `typedef _Dcomplex minfft_cmpl`. I had to change some parts of the code aswell. I hope I can send a pull request end of the week with some pre-processor directives for MSVC compiler.

**Comment by beecksche** [comment]
@aimukhin, Now, the code can be complied additonally  in C++ with MSVC (2017 & 2019, 32bit & 64bit).

But I haven't tested it! You wrote, that you used the benchFFT. Do you have a code snippet, or a readme how to use benchFFT with minfft?

**Comment by aimukhin** [comment]
@beecksche minfft is included in the current master benchFFT

**Comment by aimukhin** [comment]
@beecksche I just pushed two commits that fix the library code for MSVC. Hopefully, changing `double complex` to `_Dcomplex` should be the only thing you have to do. Please try it and let me know.

**Comment by beecksche** [comment]
That's awesome! Works perfectly, and a much more elegant way than mine.

In the header I also had to add
```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
``` 

for C++ compiling.

**Comment by aimukhin** [comment]
@beecksche I just pushed commits to further improve compatibility. If C99 complex is not available (as with MSVC), then minfft_cmpl is an array of two reals, which is binary compatible with `_Dcomplex` and `complex<double>`. You only have to cast pointers:
```
_Dcomplex z[N],w[N];
or
complex<double> z[N],w[N];
...
minfft_dft((minfft_cmpl*)z,(minfft_cmpl*)w,a);
```
Also I added extern "C" wrapper to the header file.
Hope you can now use the library without any modifications.

**Comment by beecksche** [comment]
@aimukhin Awesome, worked perfectly.
